import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

// Long-form pages on the site (generated by scripts/sync-content.mjs).
// Currently just the model card; SUMMARY/CRISIS/LOG pages were removed Sep 9.
const docs = defineCollection({
  loader: glob({
    pattern: "**/*.md",
    base: "./src/content/docs",
    generateId: ({ entry }) => entry.replace(/\.md$/, ""),
  }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
  }),
});

export const collections = { docs };
